movie_app/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :viewings
  resources :movies
  resources :movies
  resources :users
  resources :viewings
  root 'movies#index'

end

movie_app/app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :viewings
end

movie_app/app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :viewings
  
end

movie_app/app/models/viewing.rb
class Viewing < ActiveRecord::Base
  belongs_to :movie
  has_and_belongs_to_many :users
end

movie_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

movie_app/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :about, :review)
    end
end

movie_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

movie_app/app/controllers/viewings_controller.rb
class ViewingsController < ApplicationController
  before_action :set_viewing, only: [:show, :edit, :update, :destroy]

  # GET /viewings
  # GET /viewings.json
  def index
    @viewings = Viewing.all
  end

  # GET /viewings/1
  # GET /viewings/1.json
  def show
  end

  # GET /viewings/new
  def new
    @viewing = Viewing.new
  end

  # GET /viewings/1/edit
  def edit
  end

  # POST /viewings
  # POST /viewings.json
  def create
    @viewing = Viewing.new(viewing_params)

    respond_to do |format|
      if @viewing.save
        format.html { redirect_to @viewing, notice: 'Viewing was successfully created.' }
        format.json { render :show, status: :created, location: @viewing }
      else
        format.html { render :new }
        format.json { render json: @viewing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /viewings/1
  # PATCH/PUT /viewings/1.json
  def update
    respond_to do |format|
      if @viewing.update(viewing_params)
        format.html { redirect_to @viewing, notice: 'Viewing was successfully updated.' }
        format.json { render :show, status: :ok, location: @viewing }
      else
        format.html { render :edit }
        format.json { render json: @viewing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /viewings/1
  # DELETE /viewings/1.json
  def destroy
    @viewing.destroy
    respond_to do |format|
      format.html { redirect_to viewings_url, notice: 'Viewing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_viewing
      @viewing = Viewing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def viewing_params
      params.require(:viewing).permit(:viewing_type, :when_viewed)
    end
end

movie_app/app/helpers/application_helper.rb
module ApplicationHelper
end

movie_app/app/helpers/movies_helper.rb
module MoviesHelper
end

movie_app/app/helpers/users_helper.rb
module UsersHelper
end

movie_app/app/helpers/viewings_helper.rb
module ViewingsHelper
end

movie_app/app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :about %><br>
    <%= f.text_field :about %>
  </div>
  <div class="field">
    <%= f.label :review %><br>
    <%= f.text_area :review %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

movie_app/app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

movie_app/app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>About</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.about %></td>
        <td><%= movie.review %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

movie_app/app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

movie_app/app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>About:</strong>
  <%= @movie.about %>
</p>

<p>
  <strong>Review:</strong>
  <%= @movie.review %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

movie_app/app/views/viewings/_form.html.erb
<%= form_for(@viewing) do |f| %>
  <% if @viewing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@viewing.errors.count, "error") %> prohibited this viewing from being saved:</h2>

      <ul>
      <% @viewing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :viewing_type %><br>
    <%= f.text_field :viewing_type %>
  </div>
  <div class="field">
    <%= f.label :when_viewed %><br>
    <%= f.text_field :when_viewed %>
  </div>
  <div class="field">
    <%= f.label :movie_id %><br>
    <%= f.select("movie_id", Movie.all.map { |m| [m.title, m.id]}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

movie_app/app/views/viewings/edit.html.erb
<h1>Editing Viewing</h1>

<%= render 'form' %>

<%= link_to 'Show', @viewing %> |
<%= link_to 'Back', viewings_path %>

movie_app/app/views/viewings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Viewings</h1>

<table>
  <thead>
    <tr>
      <th>Viewing type</th>
      <th>When viewed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @viewings.each do |viewing| %>
      <tr>
        <td><%= viewing.movie.try(:title) %></td>
        <td><%= viewing.viewing_type %></td>
        <td><%= viewing.when_viewed %></td>
        <td><%= link_to 'Show', viewing %></td>
        <td><%= link_to 'Edit', edit_viewing_path(viewing) %></td>
        <td><%= link_to 'Destroy', viewing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Viewing', new_viewing_path %>

movie_app/app/views/viewings/new.html.erb
<h1>New Viewing</h1>

<%= render 'form' %>

<%= link_to 'Back', viewings_path %>

movie_app/app/views/viewings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Movie</strong>
  <%= @viewing.movie.try(:title) %>
</p>

<p>
  <strong>Viewing type:</strong>
  <%= @viewing.viewing_type %>
</p>

<p>
  <strong>When viewed:</strong>
  <%= @viewing.when_viewed %>
</p>

<%= link_to 'Edit', edit_viewing_path(@viewing) %> |
<%= link_to 'Back', viewings_path %>