fantasy_league/config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :players
  root 'teams#index'

end

fantasy_league/app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team
end

fantasy_league/app/models/team.rb
class Team < ActiveRecord::Base
  has_many :players
end

fantasy_league/app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @players = Player.all.order(:last_name)
  end

  def new
    @player = Player.new
  end

  def create
    Player.create(player_params)
    redirect_to(players_path)
  end

  def show
    @player = Player.find(params[:id])
  end

  def destroy
    player = Player.find(params[:id])
    player.destroy
    redirect_to(players_path)
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    player = Player.find(params[:id])
    player.update(player_params)
    redirect_to(players_path)
  end

  private

  def player_params
    params.require(:player).permit(:first_name, :last_name, :team_id, :position, :broomstick)
  end

end

fantasy_league/app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all

  end

  def new
    @team = Team.new
  end

  def create
    Team.create(team_params)
    redirect_to(teams_path)
  end

  def show
    @team = Team.find(params[:id])
  end

  def destroy
    team = Team.find(params[:id])
    team.destroy
    redirect_to(teams_path)
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    team = Team.find(params[:id])
    team.update(team_params)
    redirect_to(teams_path)
  end

  private
  def team_params
    params.require(:team).permit(:name, :image, :founded, :mascot, :league, :last_position)
  end
end

fantasy_league/app/views/players/_form.html.erb
<div class="form">  
  <br>
  <%= form_for @player do |f| %>
    <%= f.label :first_name, "First Name:" %>
    <%= f.text_field :first_name %>
    <br>
    <br>
    <%= f.label :last_name, "Last Name:" %>
    <%= f.text_field :last_name %>
    <br>
    <br>
    <%= f.label :team_id, "Team:" %>
    <%= f.select :team_id, Team.all.map { |t| [t. name, t.id] } %>
    <br>
    <br>
    <%= f.label :position, "Position:" %>
    <%= f.select :position, %w(Seeker Chaser  Beater Keeper) %>
    <br>
    <br>
    <%= f.label :broomstick, "Broomstick:" %>
    <%= f.text_field :broomstick %>
    <br>
    <br>
    <%= f.submit button_text %>
  <% end %>
</div>

fantasy_league/app/views/players/_player.html.erb
<div class="individual">
<%= player.first_name %> <%= player.last_name %>.
<%= link_to("Show #{player.last_name}", player_path(player)) %>
<%= button_to('Delete Player', player_path(player), method: :delete, data: {confirm: 'Are you sure you want obliterate this team?'}) %>
<%= link_to('Edit Player', edit_player_path(player)) %>
<br>
</div>

fantasy_league/app/views/players/edit.html.erb
<%= render partial: "form", locals: { button_text: 'update'} %>

fantasy_league/app/views/players/index.html.erb
<%= render @players %>


<%# @players.each do |player| %>

  <%#= player.first_name %> <%#= player.last_name %>
  <%#= link_to("Show #{player.last_name}", player_path(player)) %>
  <%#= button_to('Delete Player', player_path(player), method: :delete, data: {confirm: 'Are you sure you want obliterate this team?'}) %>
  <%#= link_to('Edit Player', edit_player_path(player)) %>
  
 

<%# end %>

fantasy_league/app/views/players/new.html.erb
<%= render partial: "form", locals: { button_text: 'create'} %>

fantasy_league/app/views/players/show.html.erb
<h1><%= @player.first_name %> <%= @player.last_name %></h1>
<p>Is <%= link_to(@player.team.try(:name), team_path(@player.team.id)) %> star <%= @player.position %> and rides on a <%= @player.broomstick %>.</p>